name = "Many Roads Home"
author = "Many Roads Home project"
version = "0.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2802584b2ff4231acedf25b284b4d1096bd836815cbddcf21e226669fb1d35"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
