name = "Many Roads Home"
author = "Many Roads Home project"
version = "0.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "167f4a3f1198abf8b0e2286efea0cb97832a3398b31795c7ca12626e39993580"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
