name = "Many Roads Home"
author = "Many Roads Home project"
version = "0.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56d9a42ea06589fa8bfc5cb08bd5f23ff17bc7f8de11e2a36c9ef1ecc57b0cd0"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
