# Generate the dependency lock report from the packwiz metadata.
# Windows counterpart of report-dependencies.sh. Output must be identical, because CI
# compares the generated file against the committed one on either platform.
$ErrorActionPreference = 'Stop'

$RootDir = Split-Path -Parent $PSScriptRoot
$PackDir = Join-Path $RootDir 'pack'
$Out     = Join-Path $RootDir 'docs/mod-research/dependency-lock.md'

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Out) | Out-Null

function Field($content, $name) {
    $m = [regex]::Match($content, "(?m)^$name = `"(.*)`"")
    if ($m.Success) { $m.Groups[1].Value } else { '' }
}

$lines = @()
$lines += '# Dependency lock report'
$lines += ''
$lines += 'Generated by `scripts/report-dependencies.sh` from the packwiz metadata in'
$lines += '`pack/`. Do not edit by hand. Regenerate after any dependency change.'
$lines += ''
$lines += 'Baseline from `pack/pack.toml`:'
$lines += ''
Get-Content (Join-Path $PackDir 'pack.toml') |
    Where-Object { $_ -match '^(minecraft|fabric) = ' } |
    ForEach-Object { $lines += "    $_" }
$lines += ''
$lines += '| File | Name | Side | Modrinth project | Pinned version |'
$lines += '|---|---|---|---|---|'

Get-ChildItem -Path $PackDir -Recurse -Filter '*.pw.toml' |
    Sort-Object FullName |
    ForEach-Object {
        $c   = Get-Content $_.FullName -Raw
        $rel = $_.FullName.Substring($RootDir.Length + 1) -replace '\\', '/'
        $lines += "| ``$rel`` | $(Field $c 'name') | $(Field $c 'side') | ``$(Field $c 'mod-id')`` | ``$(Field $c 'version')`` |"
    }

Set-Content -Path $Out -Value $lines -Encoding utf8
Write-Host "report-dependencies: wrote $Out"
