#!/usr/bin/env bash
# Generate a human-readable dependency lock report from the packwiz metadata.
#
# The packwiz .pw.toml files are the source of truth. This report exists so a
# reviewer can see every pinned dependency, its exact version, and its licence in
# one place without parsing TOML by hand, and so a licence change is visible in a
# diff.
set -euo pipefail
IFS=$'\n\t'

readonly ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
readonly OUT="${ROOT_DIR}/docs/mod-research/dependency-lock.md"

mkdir -p "$(dirname "${OUT}")"
{
    echo "# Dependency lock report"
    echo
    echo "Generated by \`scripts/report-dependencies.sh\` from the packwiz metadata in"
    echo "\`pack/\`. Do not edit by hand. Regenerate after any dependency change."
    echo
    echo "Baseline from \`pack/pack.toml\`:"
    echo
    grep -E '^(minecraft|fabric) = ' "${ROOT_DIR}/pack/pack.toml" | sed 's/^/    /'
    echo
    echo "| File | Name | Side | Modrinth project | Pinned version |"
    echo "|---|---|---|---|---|"
    find "${ROOT_DIR}/pack" -name '*.pw.toml' | sort | while IFS= read -r meta; do
        rel="${meta#${ROOT_DIR}/}"
        name="$(grep -E '^name = ' "${meta}" | head -1 | sed 's/.*"\(.*\)"/\1/')"
        side="$(grep -E '^side = ' "${meta}" | head -1 | sed 's/.*"\(.*\)"/\1/')"
        proj="$(grep -E '^mod-id = ' "${meta}" | head -1 | sed 's/.*"\(.*\)"/\1/')"
        ver="$(grep -E '^version = ' "${meta}" | head -1 | sed 's/.*"\(.*\)"/\1/')"
        echo "| \`${rel}\` | ${name} | ${side} | \`${proj}\` | \`${ver}\` |"
    done
} > "${OUT}"

echo "report-dependencies: wrote ${OUT}"
